---
- name: Configure app server
  hosts: all
  become: yes
  remote_user: ubuntu
  vars:
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    app: openjdk-17-jdk
    app_name: myapp
    service_name: myapp
    jar_file: myapp-1.0.0.jar
    jar_dest_path: /opt/{{ jar_file }}

  tasks:
    - name: Install Java JDK
      apt:
        name: "{{ app }}"
        state: present
        update_cache: yes
    

    - name: Pull artifact from nexus repo
      get_url:
        url: 'http://172.31.16.4:8081/repository/maven-releases/com/example/myapp/1.0.0/myapp-1.0.0.jar'
        dest: '/opt/'
        mode: '0777'


    - name: Create systemd service file
      copy:
        dest: /etc/systemd/system/{{ service_name }}.service
        content: |
          [Unit]
          Description=Java Application {{ app_name }}
          After=network.target

          [Service]
          User=root
          ExecStart=/usr/bin/java -jar {{ jar_dest_path }}
          SuccessExitStatus=143
          Restart=on-failure
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
      notify: restart app

    - name: Enable service
      systemd:
        name: "{{ service_name }}"
        enabled: yes
        state: started

  handlers:
    - name: restart app
      systemd:
        name: "{{ service_name }}"
        state: restarted



    